### Get all products
GET https://localhost:7033/products
Accept: application/json

### Get product by id
GET https://localhost:7033/products/1
Accept: application/json

### Add product
POST https://localhost:7033/products
Content-Type: application/json

{
  "//name": "aaa"
}

### Update product
PUT https://localhost:7033/products/1
Content-Type: application/json

{
  "id": 1,
  "name": "Do A",
  "IsComplete": true
}







