### Get product by id
GET https://localhost:7033/products/tech/prod-1
Accept: application/json

### Register product
POST https://localhost:7033/products
Content-Type: application/json

{
  "productId": "PROD-1",
  "name": "MSI Laptop",
  "locationCode": "1000",
  "category": "Tech"
}

### Change location
PUT https://localhost:7033/products/tech/prod-1
Content-Type: application/json

{  
  "locationCode": "1010"
}







